name: Building gollvm
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  macOS_11_Big_Sur:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Installing automake + autoconf + libtool
        run: brew install autoconf automake libtool 
      - name: Checking the version of make, automake, autoconf and m4
        run: make --version && m4 --version && autoconf --version && automake --version
      - name: Build epoll/kqueue shim
        run: git clone https://github.com/jiixyj/epoll-shim && cd epoll-shim && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && sudo cmake --build . --target install
      - name: Clonning LLVM master branch && gollvm related repos.
        run:  cd $GITHUB_WORKSPACE && git clone https://github.com/llvm/llvm-project.git && cd llvm-project/llvm/tools && git clone https://go.googlesource.com/gollvm &&  cd gollvm && git clone https://go.googlesource.com/gofrontend && cd libgo && git clone https://github.com/libffi/libffi.git && git clone https://github.com/ianlancetaylor/libbacktrace.git
      - name: Compiling & linking gollvm
        run: cd $GITHUB_WORKSPACE && mkdir build_release && cd build_release && cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_USE_LINKER=ld -DGOLLVM_DEFAULT_LINKER=ld ../llvm-project/llvm && make -j16 gollvm && ninja GoBackendCoreTests && ./tools/gollvm/unittests/BackendCore/GoBackendCoreTests
  
  macOS_10_Catalina:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Checking if we have "go"
        run: which go
      - name: Checking Golang's version
        run: go version
      - name: Checking where are we
        run: pwd
      - name: Downloading C++ code of a CPU feature extractor
        run: wget https://gist.githubusercontent.com/advancedwebdeveloper/09033869445a09a2e297a73387d46c41/raw/bf7dac33e256621c445f9e61f88a832e50d901a3/llvm_cpu_features_investigation.cpp
      - name: Checking Clang's version
        run: clang --version
      - name: Building CPU feature extractor
        run: clang -I/usr/local/opt/llvm/include/llvm-c -I/usr/local/opt/llvm/include -I/usr/local/Cellar/llvm/11.0.0/ -L/usr/local/opt/llvm/lib -L/usr/local/Cellar/llvm/11.0.0/lib -lLLVM -lstdc++ llvm_cpu_features_investigation.cpp
      - name: Checking host target
        run: llc-11 --version
